before_install:
  - chmod +x ./mvnw

language: java

deploy:
  provider: heroku
  api-key: $HEROKU_API_KEY
  app: test-travis-ci-cd

branches:
  only:
    - master


notifications:
  slack: lll-dsi3462:pP6YA8n1oxveDKsT2yxp6GTC
  on_success: always  # change: send a notification when the build status changes.
  on_failure: always  # always: always send a notification.
  template:
    - "Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`."
    - "Execution time: *%{duration}*"
    - "Message: %{message}"

addons:
  sonarcloud:
    organization: "mjiason"
    token:
      secure: "LDgLnwm30hWDFoNqmSUFUCwfe77Wgp7BG4zQjBxAzZUjOlDWT+TA1SGn9z1aX8zuXYbf4BUsPvlWzszRNX6d7co7PKqZXtJsaKBqWpmQBmkCfqCWoX2dV43+iL+zBeocxT0b8ZynbKQaMJ6H+CQXTbVGYcKSLgz6v0VriG7r2lrCTwriAuQlf0LzpTcV49A5lrAjGLAidM5q8hc+5eZmlsgsxkFcRcNTOgXcG9FO1qCknHdLLlXUpfF/Bw3CBrZx0K8DhO6cwnYYaBeJlBD2MVU0LrPXFt8y1TVysdmjPKKoew9n36PIM3M/dWZ+R506dS9T4+tpFYJWK3QESkgBAtvqxYmf+gabq9N5Nb+Z20CQH/J4sEPGl5qHv7I1yF9f2AMSgYpp+Cckvndb5kUvhsswO1sj1vszps1yKXW6G56tlGpM3cZiNXRkX1LOD0VeQFLSxuLHt0jGvy9vEkwcXufZH38PuAR4ifpC9g+NmFqsdwiYPcFbvemJBydGOmGuWKDP9bPGboKF/AtjdAgox81+xct3djfCN3S5W5cT9Em0/Q14/FVBePa05Ow/MpwqgGozWB1gN6VopG1HFTZCX9V0PHAJRXMsau+i3diZcokBEDZTqLDlvAeQKoV1PV/ZQ1aMYYa5sw/ihQYID6+exOFThw42x/8TGA7nwEBGeVo=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=TestCiCd