before_install:
- chmod +x ./mvnw
language: java
notifications:
  slack:
    secure: SdGBTZh1o8Ni8wx6DLirJu+sMN6+bemgv/0wIovxs5kOCPkRSJs8VV23/2t+MtIKbiy9fPtoPnxiZrhNrjdm/1CxQWI3JBMOfhs4/FNqfSITdR4Iroy1Mf49ls9OLOlEr6rcDC/ynIKtUHBUeZF3E9LC5V/WpLkk/R8u/49ZIRnYeugaiKXWt4TElzivOVVcQQjp/vNtP/toOksrJLPY08ZgkK0C7KmxdY4s/5+N6rMc7y3XFc08mWfSiFu7wICLwN1hMkuWbXUyWgIrRgn3IbsbbvM8mEljB0N2nhTF3RHFtWvMeckehdlL1aJjflKwb414Hu4MQvHoBngFUltLNHFiDiKLmtl1tRmdHbKxTN+8AhjKYFt3iGogQrWIxxCp/8drTzyBQlqPlrIxYgsueVoVXf/+o9G11eR4wYGktlYjDERRc0M2affe3GaTuxdsOzhyjQ2NfafT4GvArE9hciJZSO1QYlEt3jF2gG3ZXlgRzKI2AXRLW8X0RvtYr1/m77lE0GPtCFM6DUZLV0j9xRTb8MtWKZ6lPHsY9qaLWI821jc3xKjyKYHCGzhPPL+glz/ocMb2xyNoYva/zPS80lTDxxO4RaNFT58CjbX0FhBkNEwTQJfmwoQPR6p9SOo8ziXTEBi9bA9+srJidEBM9xcGdC/zHiYLqdb8WPpqxOo=
branches:
  only:
  - master
