before_install:
  - chmod +x ./mvnw
language: java

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: test-trevis-ci-cd
branches:
  only:
    - master


notifications:
  slack: lll-dsi3462:pP6YA8n1oxveDKsT2yxp6GTC
