on: push
name: Slack Notification Demo
jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Slack Notification
      uses: partnerhero/action-webhook-slack-notify@v2.1.0
      env:
        SLACK_WEBHOOK: https://hooks.slack.com/services/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
